# Generated by Django 5.2.7 on 2025-10-03 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fort_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_reference', models.BooleanField(default=False)),
                ('fort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.fort')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StructuralAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnn_distance', models.FloatField()),
                ('ssim_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical')], max_length=20)),
                ('risk_score', models.IntegerField()),
                ('changes_detected', models.IntegerField()),
                ('total_area_affected', models.FloatField()),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='analysis_results/')),
                ('analysis_results', models.JSONField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('current_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_current', to='home.fortimage')),
                ('fort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='home.fort')),
                ('previous_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_previous', to='home.fortimage')),
            ],
            options={
                'verbose_name_plural': 'Structural Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
