# Generated by Django 5.2.3 on 2026-02-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralanalysis',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='user_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
