# Generated by Django 5.2.3 on 2026-03-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_structuralanalysis_is_false_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralanalysis',
            name='climate_stress_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='final_heritage_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuralanalysis',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
