# Generated by Django 6.0.3 on 2026-03-25 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_structuralanalysis_climate_stress_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FortDamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fort_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("Structural Crack", "Structural Crack"),
                            ("Wall Damage", "Wall Damage"),
                            ("Foundation Issue", "Foundation Issue"),
                            ("Water Seepage", "Water Seepage"),
                            ("Stone Erosion", "Stone Erosion"),
                            ("Vegetation Overgrowth", "Vegetation Overgrowth"),
                            ("Vandalism", "Vandalism"),
                            ("Collapse Risk", "Collapse Risk"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Minor", "Minor"),
                            ("Moderate", "Moderate"),
                            ("Severe", "Severe"),
                            ("Critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reporter_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Reviewed", "Reviewed"),
                            ("Action Taken", "Action Taken"),
                            ("Dismissed", "Dismissed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fort Damage Report",
                "verbose_name_plural": "Fort Damage Reports",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="damage_reports/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.fortdamagereport",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
