# Generated by Django 6.0.3 on 2026-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_issuereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurgSevakReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('sevak_name', models.CharField(max_length=200)),
                ('sevak_email', models.EmailField(max_length=254)),
                ('sevak_phone', models.CharField(blank=True, max_length=20)),
                ('fort_name', models.CharField(max_length=200)),
                ('fort_section', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('suggestions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes visible to DurgSevak when status updates')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
