# Generated by Django 6.0.3 on 2026-03-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_durgsevakreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='durgsevakreport',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'DurgSevak Report'},
        ),
        migrations.AddField(
            model_name='durgsevakreport',
            name='actioned_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='durgsevakreport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes sent to the DurgSevak when status changes'),
        ),
        migrations.AlterField(
            model_name='durgsevakreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='durgsevakreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed / No Action')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed / No Action')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='home.durgsevakreport')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
